// react/src/client/component/disc/DiscsPage.js
import React, { Component, PropTypes } from 'react';
import { graphql } from 'react-apollo';
import gql from 'graphql-tag';
import Disc from './DiscComponent';
import NewDisc from './NewDiscComponent';

/* eslint-disable no-console */
class DiscsPage extends Component { 
    constructor(props, context) {
        super(props, context);
    }
    
    render() {   
        const discs = this.props.data.discs;
        
        return (
            <div>
                <h3>Your music store is here (in React)!</h3>
                <Disc discs={discs} />
                <div style={{paddingTop: '10px'}}>
                    <NewDisc data={this.props.data} />
                </div>
            </div>
        );
    }
}

// We use the gql tag to parse our query string into a query document
const CurrentDiscsForLayout = gql`
  query CurrentDiscsForLayout {
      discs {
          title
          artist
          year
          id
      }
  }
`;

DiscsPage.propTypes = {
    data: PropTypes.shape({
        loading: PropTypes.bool.isRequired,
        discs: PropTypes.array
    }).isRequired,
};


export default graphql(CurrentDiscsForLayout)(DiscsPage);

// angular/apollo-client-angular-example/src/app/discs-page/discs-page.component.ts
import { Component, OnInit } from '@angular/core';
import { Angular2Apollo } from 'angular2-apollo';
import gql from 'graphql-tag';

const CurrentDiscsForLayout = gql`
  query CurrentDiscsForLayout {
      discs {
          title
          artist
          year
          id
      }
  }
`;

@Component({
  selector: 'app-discs-page',
  templateUrl: './discs-page.component.html',
  styleUrls: ['./discs-page.component.css']
})
export class DiscsPageComponent implements OnInit {
  loading: boolean;
  discs: any;

  constructor(private apollo: Angular2Apollo) { }

  ngOnInit() {
    this.apollo.watchQuery({
      query: CurrentDiscsForLayout
    }).subscribe(({data}) => {
      this.loading = data.loading;
      this.discs = data.discs;
    });
  }

}

<div *ngIf="discs && discs.length">
    <h3>Your music store is here!</h3>
    <ul>
        <li *ngFor="let disc of discs">{{disc.title}} - {{disc.artist}} ({{disc.year}})</li>
    </ul>
    <div >
        <!-- Area for mutation -->
    </div>
</div>
